# Generated by Django 5.2.8 on 2025-11-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id_encargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo_institucional', models.EmailField(max_length=150)),
                ('correo_personal', models.EmailField(max_length=150)),
                ('grado', models.CharField(max_length=50)),
                ('direccion_domicilio', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='estudiantes.encargado')),
            ],
        ),
    ]
