# Generated by Django 5.2.8 on 2025-11-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_colegio_procedencia_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
    ]
