# Generated by Django 5.2.8 on 2025-11-26 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_remove_encargado_estado_remove_estudiante_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_accion', models.CharField(choices=[('crear_estudiante', 'Creó estudiante'), ('editar_estudiante', 'Editó estudiante'), ('eliminar_estudiante', 'Eliminó estudiante'), ('crear_encargado', 'Creó encargado'), ('editar_encargado', 'Editó encargado'), ('eliminar_encargado', 'Eliminó encargado'), ('enviar_comunicacion', 'Envió comunicación'), ('eliminar_comunicacion', 'Eliminó comunicación')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
