# Generated by Django 5.2.8 on 2026-06-26 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_encargado_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador General'), ('director', 'Director'), ('administrador', 'Administrador'), ('profesor', 'Profesor'), ('encargado', 'Encargado')], default='profesor', max_length=20)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador General'), ('director', 'Director'), ('administrador', 'Administrador'), ('profesor', 'Profesor'), ('encargado', 'Encargado')], max_length=20)),
                ('vista', models.CharField(max_length=50)),
                ('puede_ver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'unique_together': {('rol', 'vista')},
            },
        ),
    ]
