# Generated by Django 5.2.8 on 2026-06-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_perfilusuario_permisorol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='encargado_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='estudiantes.encargado'),
        ),
    ]
