# Generated by Django 5.2.8 on 2026-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
