# Generated by Django 5.2.8 on 2026-04-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='año_lectivo',
        ),
    ]
