# Generated by Django 5.2.8 on 2026-06-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_curso_año_lectivo'),
        ('estudiantes', '0007_perfilusuario_permisorol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nota',
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='cursos.curso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscritos', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Estudiante en Curso',
                'verbose_name_plural': 'Estudiantes en Cursos',
                'unique_together': {('id_estudiante', 'id_curso')},
            },
        ),
    ]
