# Generated by Django 5.2.14 on 2026-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='identificador',
            field=models.CharField(blank=True, help_text='Modelo, serie, número de identificación u otro identificador del activo', max_length=200, null=True),
        ),
    ]
