# Generated by Django 5.2.8 on 2025-11-21 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id_correo', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_correo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorreoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_correo', models.ForeignKey(db_column='id_correo', on_delete=django.db.models.deletion.CASCADE, related_name='correo_estudiante', to='comunicaciones.correo')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='correo_estudiante', to='estudiantes.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='correo',
            name='estudiantes',
            field=models.ManyToManyField(related_name='correos', through='comunicaciones.CorreoEstudiante', to='estudiantes.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='correoestudiante',
            constraint=models.UniqueConstraint(fields=('id_correo', 'id_estudiante'), name='pk_correo_estudiante'),
        ),
    ]
