# Generated by Django 5.2.8 on 2026-03-23 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(help_text='Archivos permitidos: PDF, DOC, DOCX, XLS, XLSX, PNG, JPG, JPEG, GIF', upload_to='comunicaciones/%Y/%m/%d/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_correo', models.ForeignKey(db_column='id_correo', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='comunicaciones.correo')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
    ]
